                     RM = /bin/rm -f
                     CP = /bin/cp
                 LDLIBS = ../lib/libXpm.a -lGLw -lGLU -lGL -lSgm -lXm -lX11 -lXt -lm
                  IMAGE = gmorph2b8
                     CC = cc
                ROOTDIR = ..
                 SRCDIR = .
#               COPTIONS = -32 -O2 -xansi -g3 -fullwarn -I../include # IRIX for debug
               COPTIONS = -32 -O2 -xansi -I../include -I/usr/local/include -I/usr/X11/include # IRIX
#              COPTIONS = -O2 -xansi -fullwarn # IRIX with fullWarning
#             LDOPTIONS = -O2 -xansi -p  # IRIX for prof
              LDOPTIONS = -32 -O2 -xansi
               CINCLUDE = 
                 CFLAGS = $(COPTIONS) $(CINCLUDE)
                DATADIR = $(SRCDIR)/data
                   OBJS = $(SRCDIR)/main.o \
                          $(SRCDIR)/smd.o \
		          $(SRCDIR)/window.o \
			  $(SRCDIR)/gldraw.o \
			  $(SRCDIR)/draw.o \
			  $(SRCDIR)/busy.o \
  			  $(SRCDIR)/pick.o \
			  $(SRCDIR)/edit.o \
			  $(SRCDIR)/sellist.o \
			  $(SRCDIR)/colorc.o \
			  $(SRCDIR)/file.o \
			  $(SRCDIR)/screen.o \
			  $(SRCDIR)/ppd.o \
			  $(SRCDIR)/ppdsolid.o \
			  $(SRCDIR)/ppdpart.o \
			  $(SRCDIR)/ppdface.o \
			  $(SRCDIR)/ppdloop.o \
			  $(SRCDIR)/ppdvertex.o \
			  $(SRCDIR)/ppdnormal.o \
			  $(SRCDIR)/ppdedge.o \
			  $(SRCDIR)/ppdlist.o \
			  $(SRCDIR)/oppd.o \
			  $(SRCDIR)/prique.o \
			  $(SRCDIR)/sgprique.o \
			  $(SRCDIR)/quadtree.o \
			  $(SRCDIR)/loop.o \
			  $(SRCDIR)/gmorph.o \
			  $(SRCDIR)/grouping.o \
			  $(SRCDIR)/harmonic.o \
			  $(SRCDIR)/correspond.o \
			  $(SRCDIR)/morphvec.o \
			  $(SRCDIR)/paths.o \
			  $(SRCDIR)/sgraph.o \
			  $(SRCDIR)/sgpaths.o \
			  $(SRCDIR)/hppd.o \
			  $(SRCDIR)/hppdlod.o \
			  $(SRCDIR)/hgppd.o \
			  $(SRCDIR)/hged.o \
			  $(SRCDIR)/glppd.o \
			  $(SRCDIR)/ps.o \
			  $(SRCDIR)/image.o \
			  $(SRCDIR)/sgiimage.o \
			  $(SRCDIR)/linbcg.o \
			  $(SRCDIR)/trisquare.o \
			  $(SRCDIR)/matlib.o \
			  $(SRCDIR)/veclib.o \
			  $(SRCDIR)/Progress.o \
			  $(SRCDIR)/time.o
                   CORE = core

all: $(IMAGE)

$(IMAGE): $(OBJS)
	$(RM) $(IMAGE) $(CORE)
	$(CC) $(LDOPTIONS) -o $(IMAGE) $(SMDOBJS) $(OBJS) $(LDLIBS)
	$(CP) $(IMAGE) $(ROOTDIR)/bin

clean:
	$(RM) $(OBJS) $(CORE) $(IMAGE)
